version: "3.8"
services:
  aspire-dashboard:
    container_name: "aspire-dashboard"
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:8.0.0-preview.5"
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: "true"
    ports:
    - target: 18888
      published: 18888
    - target: 18889
      published: 4317
    restart: unless-stopped
  cache:
    container_name: "cache"
    image: "docker.io/redis/redis-stack-server:latest"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:4317"
    ports:
    - target: 6379
      published: 6379
    restart: unless-stopped
  messaging:
    container_name: "messaging"
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:4317"
    volumes:
    - "trace-apphost-messaging-data:/var/lib/rabbitmq"
    ports:
    - target: 5672
      published: 5672
    - target: 15672
      published: 15672
    restart: unless-stopped
  db:
    container_name: "db"
    image: "docker.io/postgis/postgis:15-3.3"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:4317"
    volumes:
    - "trace-apphost-db-data:/var/lib/postgresql/data"
    ports:
    - target: 5432
      published: 5432
    restart: unless-stopped
  service-core:
    container_name: "service-core"
    image: "ghcr.io/drolx/trace-service-core:0.0.1-preview.10"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      ConnectionStrings__cache: "cache:6379"
      ConnectionStrings__messaging: "amqp://guest:guest@messaging:5672"
      ConnectionStrings__trace: "Host=db;Port=5432;Username=postgres;Password=postgres;Database=trace"
      MessagingUser: "guest"
      MessagingPass: "guest"
      DbUser: "postgres"
      DbPass: "postgres"
      CassandraHost: "scylladb"
      CassandraPort: "9042"
      CassandraUser: "cassandra"
      CassandraPass: "cassandra"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:4317"
    ports:
    - target: 8080
      published: 10000
    - target: 8443
      published: 10001
    restart: unless-stopped
  service-integration:
    container_name: "service-integration"
    image: "ghcr.io/drolx/trace-service-integration:0.0.1-preview.10"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      ConnectionStrings__cache: "cache:6379"
      ConnectionStrings__messaging: "amqp://guest:guest@messaging:5672"
      ConnectionStrings__trace: "Host=db;Port=5432;Username=postgres;Password=postgres;Database=trace"
      MessagingUser: "guest"
      MessagingPass: "guest"
      DbUser: "postgres"
      DbPass: "postgres"
      CassandraHost: "scylladb"
      CassandraPort: "9042"
      CassandraUser: "cassandra"
      CassandraPass: "cassandra"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:4317"
    ports:
    - target: 8080
      published: 10002
    - target: 8443
      published: 10003
    restart: unless-stopped
  service-navigation:
    container_name: "service-navigation"
    image: "ghcr.io/drolx/trace-service-navigation:0.0.1-preview.10"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      ConnectionStrings__cache: "cache:6379"
      ConnectionStrings__messaging: "amqp://guest:guest@messaging:5672"
      ConnectionStrings__trace: "Host=db;Port=5432;Username=postgres;Password=postgres;Database=trace"
      MessagingUser: "guest"
      MessagingPass: "guest"
      DbUser: "postgres"
      DbPass: "postgres"
      CassandraHost: "scylladb"
      CassandraPort: "9042"
      CassandraUser: "cassandra"
      CassandraPass: "cassandra"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:4317"
    ports:
    - target: 8080
      published: 10004
    - target: 8443
      published: 10005
    restart: unless-stopped
  service-gateway:
    container_name: "service-gateway"
    image: "ghcr.io/drolx/trace-service-gateway:0.0.1-preview.10"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      ConnectionStrings__cache: "cache:6379"
      services__service-core__http__0: "http://service-core:8080"
      services__service-integration__http__0: "http://service-integration:8080"
      services__service-navigation__http__0: "http://service-navigation:8080"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:4317"
    ports:
    - target: 8080
      published: 10006
    - target: 8443
      published: 10007
    restart: unless-stopped
  frontend:
    container_name: "frontend"
    image: "ghcr.io/drolx/trace-frontend:0.0.1-preview.10"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      ConnectionStrings__cache: "cache:6379"
      services__service-gateway__http__0: "http://service-gateway:8080"
      services__geocoding: "https://nominatim.openstreetmap.org/"
      services__routing: "https://valhalla.openstreetmap.de/"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:4317"
    ports:
    - target: 8080
      published: 10008
    - target: 8443
      published: 10009
    restart: unless-stopped
  website:
    container_name: "website"
    image: "ghcr.io/drolx/trace-website:0.0.1-preview.10"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      ConnectionStrings__cache: "cache:6379"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:4317"
    ports:
    - target: 8080
      published: 10010
    - target: 8443
      published: 10011
    restart: unless-stopped
  manager:
    container_name: "manager"
    image: "ghcr.io/drolx/trace-manager:0.0.1-preview.10"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      ConnectionStrings__cache: "cache:6379"
      ConnectionStrings__messaging: "amqp://guest:guest@messaging:5672"
      ConnectionStrings__trace: "Host=db;Port=5432;Username=postgres;Password=postgres;Database=trace"
      MessagingUser: "guest"
      MessagingPass: "guest"
      DbUser: "postgres"
      DbPass: "postgres"
      CassandraHost: "scylladb"
      CassandraPort: "9042"
      CassandraUser: "cassandra"
      CassandraPass: "cassandra"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:4317"
    ports:
    - target: 8080
      published: 10012
    - target: 8443
      published: 10013
    restart: unless-stopped
  scylladb:
    container_name: "scylladb"
    image: "scylladb/scylla:5.4"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:4317"
    volumes:
    - "scylladb:/var/lib/scylla"
    ports:
    - target: 9042
      published: 9042
    restart: unless-stopped
volumes:
  trace-apphost-messaging-data: {}
  trace-apphost-db-data: {}
  scylladb: {}
