version: "3.8"
services:
  aspire-dashboard:
    container_name: "aspire-dashboard"
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:8.0.0-preview.5"
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: "true"
    ports:
    - target: 18888
      published: 18888
    - target: 18889
      published: 4317
    restart: unless-stopped
  service-core:
    container_name: "service-core"
    image: "ghcr.io/drolx/trace-service-core:0.0.1-preview.6"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      MessagingUser: "guest"
      MessagingPass: "guest"
      DbUser: "postgres"
      DbPass: "postgres"
      CassandraPort: "guest"
      CassandraUser: "cassandra"
      CassandraPass: "cassandra"
      ConnectionStrings__cache: "cache:6379"
      ConnectionStrings__messaging: "amqp://guest:guest@messaging:5672"
      ConnectionStrings__trace: "Host=db;Port=5432;Username=postgres;Password=postgres;Database=trace"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:4317"
    ports:
    - target: 8080
      published: 10000
    - target: 8443
      published: 10001
    restart: unless-stopped
  service-integration:
    container_name: "service-integration"
    image: "ghcr.io/drolx/trace-service-integration:0.0.1-preview.6"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      MessagingUser: "guest"
      MessagingPass: "guest"
      DbUser: "postgres"
      DbPass: "postgres"
      CassandraPort: "guest"
      CassandraUser: "cassandra"
      CassandraPass: "cassandra"
      ConnectionStrings__cache: "cache:6379"
      ConnectionStrings__messaging: "amqp://guest:guest@messaging:5672"
      ConnectionStrings__trace: "Host=db;Port=5432;Username=postgres;Password=postgres;Database=trace"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:4317"
    ports:
    - target: 8080
      published: 10002
    - target: 8443
      published: 10003
    restart: unless-stopped
  service-navigation:
    container_name: "service-navigation"
    image: "ghcr.io/drolx/trace-service-navigation:0.0.1-preview.6"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      MessagingUser: "guest"
      MessagingPass: "guest"
      DbUser: "postgres"
      DbPass: "postgres"
      CassandraPort: "guest"
      CassandraUser: "cassandra"
      CassandraPass: "cassandra"
      ConnectionStrings__cache: "cache:6379"
      ConnectionStrings__messaging: "amqp://guest:guest@messaging:5672"
      ConnectionStrings__trace: "Host=db;Port=5432;Username=postgres;Password=postgres;Database=trace"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:4317"
    ports:
    - target: 8080
      published: 10004
    - target: 8443
      published: 10005
    restart: unless-stopped
  gateway:
    container_name: "gateway"
    image: "ghcr.io/drolx/trace-gateway:0.0.1-preview.6"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      services__service-core__http__0: "http://service-core:8080"
      services__service-integration__http__0: "http://service-integration:8080"
      services__service-navigation__http__0: "http://service-navigation:8080"
      ConnectionStrings__cache: "cache:6379"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:4317"
    ports:
    - target: 8080
      published: 10006
    - target: 8443
      published: 10007
    restart: unless-stopped
  frontend:
    container_name: "frontend"
    image: "ghcr.io/drolx/trace-frontend:0.0.1-preview.6"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      services__gateway__http__0: "http://gateway:8080"
      services__geocoding: "https://nominatim.openstreetmap.org/"
      services__routing: "https://valhalla.openstreetmap.de/"
      ConnectionStrings__cache: "cache:6379"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:4317"
    ports:
    - target: 8080
      published: 10008
    - target: 8443
      published: 10009
    restart: unless-stopped
  manager:
    container_name: "manager"
    image: "ghcr.io/manager:0.0.1-preview.6"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      MessagingUser: "guest"
      MessagingPass: "guest"
      DbUser: "postgres"
      DbPass: "postgres"
      CassandraPort: "guest"
      CassandraUser: "cassandra"
      CassandraPass: "cassandra"
      ConnectionStrings__cache: "cache:6379"
      ConnectionStrings__messaging: "amqp://guest:guest@messaging:5672"
      ConnectionStrings__trace: "Host=db;Port=5432;Username=postgres;Password=postgres;Database=trace"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:4317"
    ports:
    - target: 8080
      published: 10010
    - target: 8443
      published: 10011
    restart: unless-stopped
  cache:
    container_name: "cache"
    image: "docker.io/redis/redis-stack-server:7.2.0-v10"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:4317"
    ports:
    - target: 6379
      published: 6379
    restart: unless-stopped
  messaging:
    container_name: "messaging"
    image: "rabbitmq:3"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:4317"
    ports:
    - target: 5672
      published: 5672
    restart: unless-stopped
  db:
    container_name: "db"
    image: "postgis/postgis:15-3.3"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:4317"
    ports:
    - target: 5432
      published: 5432
    restart: unless-stopped
  warehouse:
    container_name: "warehouse"
    image: "scylladb/scylla:5.4"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:4317"
    ports:
    - target: 9042
      published: 9042
    - target: 9160
      published: 9160
    restart: unless-stopped
