---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: messaging
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: messaging
    spec:
      containers:
      - name: messaging
        image: rabbitmq:3-management
        imagePullPolicy: 
        envFrom:
        - configMapRef:
            name: messaging-env
      terminationGracePeriodSeconds: 180