version: "3"

volumes:
  db:

services:
  db:
    image: docker.io/postgis/postgis:15-3.3
    container_name: db
    hostname: db
    restart: unless-stopped
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trace
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
    volumes:
      - db:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    networks:
      default:
        ipv4_address: 192.168.55.30
