version: '3'

services:
  server:
    image: gpproton/nominatim-nigeria-ghana
    volumes:
      - ${STORE_ROOT}/coder/:/srv/nominatim/backups/:rw
    environment:
      # RESTORE | CREATE
      - 'NOMINATIM_MODE=RESTORE'
      - 'NOMINATIM_PBF_URL=https://download.geofabrik.de/africa/nigeria-latest.osm.pbf'
      - 'NOMINATIM_THREADS=8'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
        delay: 30s
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.1'
          memory: 64M
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 30s
      timeout: 3m
      retries: 10

