version: '3'

x-app: &app
  environment: &app-env
    ASPNETCORE_URLS: "http://+:8080"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    ConnectionStrings__cache: "cache:6379,abortConnect=false,AllowAdmin=true"
    ConnectionStrings__messaging: "amqp://guest:guest@messaging:5672"
    ConnectionStrings__db: "Host=db;Port=5432;Database=trace;Username=postgres;Password=trace;Timeout=15;Pooling=true;MinPoolSize=1;MaxPoolSize=20;ConnectionLifeTime=15"
    services__geocoding: "https://nominatim.openstreetmap.org"
    services__routing: "https://valhalla.openstreetmap.de"
    services__gateway__0: "http://gateway:8080"
    services__gateway__1: "https://gateway:8443"
    services__service-core__0: "http://service-core:8080"
    services__service-core__1: "https://service-core:8443"
    services__service-integration__0: "http://service-integration:8080"
    services__service-integration__1: "https://service-integration:8443"
    services__service-navigation__0: "http://service-navigation:8080"
    services__service-navigation__1: "https://service-navigation:8443"

services:
  manager:
    <<: *app
    image: ${REGISTRY}/trace-manager:${VERSION}
    build:
      context: ..
      dockerfile: Manager/Dockerfile
    environment:
      <<: *app-env
    ports:
      - 4590:8080

  frontend:
    <<: *app
    image: ${REGISTRY}/trace-frontend:${VERSION}
    build:
      context: ..
      dockerfile: Host/Frontend/Dockerfile
    environment:
      <<: *app-env
    ports:
      - 4580:8080

  gateway:
    <<: *app
    image: ${REGISTRY}/trace-gateway:${VERSION}
    build:
      context: ..
      dockerfile: Host/Gateway/Dockerfile
    environment:
      <<: *app-env
    ports:
      - 4570:8080

  service-core:
    <<: *app
    image: ${REGISTRY}/trace-service-core:${VERSION}
    build:
      context: ..
      dockerfile: Service/Core/Dockerfile
    environment:
      <<: *app-env
    ports:
      - 4571:8080

  service-integration:
    <<: *app
    image: ${REGISTRY}/trace-service-integration:${VERSION}
    build:
      context: ..
      dockerfile: Service/Integration/Dockerfile
    environment:
      <<: *app-env
    ports:
      - 4572:8080

  service-navigation:
    <<: *app
    image: ${REGISTRY}/trace-service-navigation:${VERSION}
    build:
      context: ..
      dockerfile: Service/Navigation/Dockerfile
    environment:
      <<: *app-env
    ports:
      - 4573:8080
