version: '3'

x-app: &app
  environment: &app-env
    ASPNETCORE_URLS: "http://+:8080"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    MessagingUser: "guest"
    MessagingPass: "guest"
    DbUser: "postgres"
    DbPass: "postgres"
    CassandraPort: 9042
    CassandraUser: "cassandra"
    CassandraPass: "cassandra"
    ConnectionStrings__cache: "cache:6379,abortConnect=false,AllowAdmin=true"
    ConnectionStrings__messaging: "amqp://guest:guest@messaging:5672"
    ConnectionStrings__trace: "Host=db;Port=5432;Username=postgres;Password=postgres;Database=trace"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
    services__geocoding: "https://nominatim.openstreetmap.org"
    services__routing: "https://valhalla.openstreetmap.de"
    services__service-gateway__0: "http://service-gateway:8080"
    services__service-gateway__1: "https://service-gateway:8443"
    services__service-core__0: "http://service-core:8080"
    services__service-core__1: "https://service-core:8443"
    services__service-integration__0: "http://service-integration:8080"
    services__service-integration__1: "https://service-integration:8443"
    services__service-navigation__0: "http://service-navigation:8080"
    services__service-navigation__1: "https://service-navigation:8443"

services:
  aspire-dashboard:
    container_name: "aspire-dashboard"
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:8.0.0-preview.5"
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: "true"
    ports:
    - target: 18888
      published: 18888
    - target: 18889
      published: 4317
    restart: unless-stopped

  manager:
    <<: *app
    image: ${REGISTRY}/trace-manager:${VERSION}
    container_name: manager
    build:
      context: .
      dockerfile: Manager/Dockerfile
    environment:
      <<: *app-env
    ports:
      - 4590:8080

  frontend:
    <<: *app
    image: ${REGISTRY}/trace-frontend:${VERSION}
    container_name: frontend
    build:
      context: .
      dockerfile: Host/Frontend/Dockerfile
    environment:
      <<: *app-env
    ports:
      - 4580:8080

  website:
    <<: *app
    image: ${REGISTRY}/trace-website:${VERSION}
    container_name: website
    build:
      context: .
      dockerfile: Host/Website/Dockerfile
    environment:
      <<: *app-env
    ports:
      - 4600:8080

  service-gateway:
    <<: *app
    image: ${REGISTRY}/trace-service-gateway:${VERSION}
    container_name: service-gateway
    build:
      context: .
      dockerfile: Host/Gateway/Dockerfile
    environment:
      <<: *app-env
    ports:
      - 4570:8080

  service-core:
    <<: *app
    image: ${REGISTRY}/trace-service-core:${VERSION}
    container_name: service-core
    build:
      context: .
      dockerfile: Service/Core/Dockerfile
    environment:
      <<: *app-env
    ports:
      - 4571:8080

  service-integration:
    <<: *app
    image: ${REGISTRY}/trace-service-integration:${VERSION}
    container_name: service-integration
    build:
      context: .
      dockerfile: Service/Integration/Dockerfile
    environment:
      <<: *app-env
    ports:
      - 4572:8080

  service-navigation:
    <<: *app
    image: ${REGISTRY}/trace-service-navigation:${VERSION}
    container_name: service-navigation
    build:
      context: .
      dockerfile: Service/Navigation/Dockerfile
    environment:
      <<: *app-env
    ports:
      - 4573:8080
