version: '3'

volumes:
  scylladb:

services:
  scylladb:
    image: scylladb/scylla:5.4
    container_name: scylladb
    hostname: scylladb
    restart: unless-stopped
    ports:
      - 9042:9042
      - 9160:9160
    volumes:
      - scylladb:/var/lib/scylla
    networks:
      default:
        ipv4_address: 192.168.55.40
