version: '3'

services:
  server:
    image: minio/minio
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          memory: 32M
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.middlewares.minio-strip.stripprefix.prefixes=/service/storage,/service/storage/'
        ## Storage CDN access
        - 'traefik.http.services.minio.loadbalancer.server.port=9000'
        - 'traefik.http.routers.minio.entrypoints=web-secure'
        - 'traefik.http.routers.minio.rule=Host(`storage.${DOMAIN}`) || Host(`staging.${DOMAIN}`) && PathPrefix(`/service/storage`)'
        - 'traefik.http.routers.minio.service=minio'
        - 'traefik.http.routers.minio.middlewares=minio-strip'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
      - '${STORE_ROOT}/minio:/data'
    ports:
      - 9001:9001
    environment:
      MINIO_UPDATE: 'off'
      MINIO_ROOT_USER: trace
      MINIO_ROOT_PASSWORD: trace@1234
      MINIO_SITE_NAME: trace-00
    command: server --address 0.0.0.0:9000 --console-address ":9001" /data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 5
