---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: manager
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: manager
    spec:
      containers:
      - name: manager
        image: ghcr.io/drolx/trace-manager:0.0.1-preview.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: manager-env
        - secretRef:
            name: manager-secrets
      terminationGracePeriodSeconds: 180
