resources:
- deployment.yml
- service.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: manager-env
  literals:
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES=true
    - services__service-integration__0=http://service-integration:8080
    - services__service-integration__1=https://service-integration:8443
    - services__service-navigation__0=http://service-navigation:8080
    - services__service-navigation__1=https://service-navigation:8443
    - ASPNETCORE_URLS=http://+:8080

secretGenerator:
- name: manager-secrets
  envs:
  - .manager.secrets
