FROM mcr.microsoft.com/devcontainers/dotnet:8.0-jammy

# [Optional] Uncomment this line to install global node packages.
# RUN su vscode -c "source /usr/local/share/nvm/nvm.sh && npm install -g <your-package-here>" 2>&1
