---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-navigation
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: service-navigation
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: service-navigation
    spec:
      containers:
      - name: service-navigation
        image: ghcr.io/drolx/trace-service-navigation:0.0.1-preview.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: service-navigation-env
        - secretRef:
            name: service-navigation-secrets
      terminationGracePeriodSeconds: 180
